<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day10numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

In [25]:
#filter | array me se valuse nikalna jo apne chaiye
arr = np.array([10,20,3,4,50,900])
arr_f = arr[arr>20]
print(arr_f)

[ 50 900]


In [26]:
arr = np.array([200,300,10,38,47,5657,34,60])
arr_f = arr[arr != 60]
print(arr_f)

[ 200  300   10   38   47 5657   34]


In [27]:
arr = np.arange(20)
arr_f = arr[(arr > 10) & (arr < 20)]
print(arr_f)

[11 12 13 14 15 16 17 18 19]


In [28]:
import numpy as np
arr = np.array([10,20,30,5,8,0,2,54,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)

[15 18]


In [29]:
#fancy indexing
arr = np.array([10,20,40,5,7,2,800])
print(arr)
arr_f = arr[[0,2]] #0 index value, 2 index value
print(arr_f)


[ 10  20  40   5   7   2 800]
[10 40]


In [30]:
#where
arr = np.array([10,20,3,4,5,88,900])
print(arr)
arr_w=np.where(arr>9,"True","false")
print(arr_w)

#question 10 -20 -> | +2


[ 10  20   3   4   5  88 900]
['True' 'True' 'false' 'false' 'false' 'True' 'True']


In [31]:
import numpy as np

arr = np.array([10,20,3,4,5,88,900])
print(arr)
new_arr = np.where((arr >= 10) & (arr <= 20), arr+2, arr*2,)

print(new_arr)

[ 10  20   3   4   5  88 900]
[  12   22    6    8   10  176 1800]


In [32]:
#adding and removing
arr1 = np.array([10,30,50])
arr2 = np.array([1,2,3])

#concatenate
arr_arr2 = np.concatenate((arr1,arr2))
print(arr_arr2)

#concatenate using 2d
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)



[10 30 50  1  2  3]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [33]:
#v-stack | vertically join | roe vise
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.vstack((arr1,arr2))
print(arr_h)

[[1 2 3]
 [4 5 6]]


In [34]:
# H-stack | Horizontally stack
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr_h = np.hstack((arr1,arr2))
print(arr_h)

[1 2 3 4 5 6]


In [35]:
#useful function
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.min(arr))
print(np.max(arr))

25.0
25.0
11.180339887498949
125.0
10
40


In [36]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr)) # sum
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))

30
2
10
6.0
6.0


In [37]:
arr = ([10,20,30,40])
print('Mean:' ,np.mean(arr)) #mean
print('Median:' ,np.median(arr)) #median
print('Standard Deviation:' ,np.std(arr)) #standard deviation
print('Variance:' ,np.var(arr)) #variance
print(np.min(arr)) #min
print(np.max(arr)) #max

Mean: 25.0
Median: 25.0
Standard Deviation: 11.180339887498949
Variance: 125.0
10
40


In [38]:
# 1. np.sum(a) -> Sum of all elements
# 2. np.mean(a) -> Average = Sum of elements / Number of elements
# 3. np.median(a) -> Middle value after sorting
# 4. np.min(a) -> Smallest value in array
# 5. np.max(a) -> Largest value in array
# 6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
# 7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
# 8. np.prod(a) -> Multiplication of all elements
# 9. np.cumsum(a) -> Cumulative (running) sum
# 10. np.cumprod(a) -> Cumulative (running) product
# 11. np.argmin(a) -> Index position of minimum value
# 12. np.argmax(a) -> Index position of maximum value
# 13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
# 14. np.unique(a) -> Returns unique values only -> Removes duplicates
# 15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
# 16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
# 17. np.ptp(a) -> Range = Max - Min
# 18. np.any(a) -> True if at least one value is True


In [39]:
#percentil
import numpy as np
arr =  np.array([10,20,30,5,55,66])
print(np.percentile(arr,20))

10.0


In [40]:
#Handling  missing value
arr = np.array([10,20,np.nan,40])
print(arr)

#isnan
print(np.isnan(arr))

#update nan by number
new_arr = np.nan_to_num(arr,nan=100)
print(new_arr)


[10. 20. nan 40.]
[False False  True False]
[ 10.  20. 100.  40.]


In [41]:
import numpy as np
sales_data = np.array([
    [1,150000,180000,220000,250000], #Paradise Biryani
    [2,120000,140000,160000,190000], #Bejing Bites
    [3,200000,230000,260000,300000], #Pizza Hub
    [4,180000,210000,240000,270000], #Burger Points
    [5,160000,185000,205000,230000] #chain Point
    ])
print(sales_data)
print(sales_data.shape)
print(sales_data.ndim)
print(sales_data.size)
print(sales_data[:,0])
print(sales_data[:,1])
print(sales_data[:,4])
print(np.max(sales_data[:,1:]))
print(np.min(sales_data[:,1:]))
print(np.sum(sales_data[:,1]))
print(np.mean(sales_data[:,4]))
print(np.sum(sales_data[:,1:],axis=1)) #sum means adding
print(np.mean(sales_data[:,1:],axis=1))  #mean means avarage

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
(5, 5)
2
25
[1 2 3 4 5]
[150000 120000 200000 180000 160000]
[250000 190000 300000 270000 230000]
300000
120000
810000
248000.0
[800000 610000 990000 900000 780000]
[200000. 152500. 247500. 225000. 195000.]


In [42]:
import numpy as np

# 1D Array (Vector) banana
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D Array (Matrix) banana
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:\n", arr2)

# Array ki shape check karna (rows, columns)
print("\nShape of arr2:", arr2.shape)  # Output: (2, 3)

1D Array: [1 2 3 4 5]

2D Array:
 [[1 2 3]
 [4 5 6]]

Shape of arr2: (2, 3)


In [43]:
#Auto generating array

import numpy as np

# Saare elements 0 ke sath array banana (Shape: 3 rows, 4 cols)
zeros_arr = np.zeros((3, 4))
print("Zeros Array:\n", zeros_arr)

# 1 se lekar 10 tak sequence generate karna
range_arr = np.arange(1, 11)
print("\nRange Array:", range_arr)  # [1 2 3 4 5 6 7 8 9 10]

# Random float values generate karna (0 aur 1 ke beech, Shape: 2x2)
random_arr = np.random.rand(2, 2)
print("\nRandom Array:\n", random_arr)

Zeros Array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Range Array: [ 1  2  3  4  5  6  7  8  9 10]

Random Array:
 [[0.43054218 0.83422041]
 [0.02472012 0.17301824]]


In [44]:
#array indexing and slicing

import numpy as np

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Kisi specific element ko nikalna (Row 1, Column 2 -> Indexing 0 se shuru hoti hai)
print("Element at row 1, col 2:", matrix[1, 2])  # Output: 60

# Pehli do rows aur pehle do columns ko slice (crop) karna
print("\nSliced Sub-matrix:\n", matrix[0:2, 0:2])
# Output:
# [[10 20]
#  [40 50]]

Element at row 1, col 2: 60

Sliced Sub-matrix:
 [[10 20]
 [40 50]]


In [45]:
#Basic Mathematical Operations (Element-wise)
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

# Element-wise Addition aur Subtraction
print("Addition:", a + b)        # [11 22 33 44]
print("Subtraction:", a - b)     # [ 9 18 27 36]

# Kisi number se direct multiply/square karna
print("Multiply by 2:", b * 2)   # [2 4 6 8]
print("Square of elements:", b**2) # [1 4 9 16]

Addition: [11 22 33 44]
Subtraction: [ 9 18 27 36]
Multiply by 2: [2 4 6 8]
Square of elements: [ 1  4  9 16]
