<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/Day7_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
#numpy
#!pip install numpy
import numpy as np

In [12]:
l = [20,30,40,50]
l*2


[20, 30, 40, 50, 20, 30, 40, 50]

In [14]:
#power of numpy
arr = np.array(l)
arr*2

array([ 40,  60,  80, 100])

In [18]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr[0]
print(arr[-1])

5


In [20]:
arr = np.zeros(10)
arr



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
arr = np.array([4]*20)
arr

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [26]:
#change value
l = [10,20,30,40]
l[0] = 100
print(l)

#numpy
arr = np.array([10,20,30,40])
arr[0] = 100
arr[-1] = 400
print(arr)

[100, 20, 30, 40]
[100  20  30 400]


In [32]:
arr = np.arange(10, 51)
#arr = np.arange(10, 51,2) #first-> start, second-> end, third->jump
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [29]:
#value add = 2
import numpy as np
l = [10,20,30,40]
#print(l+2) #add not acceptable with list

arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [39]:
arr = np.arange(100,1000,100)
#print(arr)
arr



array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [42]:
for i in range(100,200,10):
 print(i)

100
110
120
130
140
150
160
170
180
190


In [48]:
import numpy as np
# [[Row 1], [Row 2]]
matrix = np.array([[1, 2,3],
                   [3, 4,5]])

# Full array ko print karte hain
print("Yeha hai humara 2D Array:")
print(matrix)

# Ek single value nikalne ke liye

print(matrix[1, 2])

Yeha hai humara 2D Array:
[[1 2 3]
 [3 4 5]]
5


In [51]:
#simple 2d example
print ("list start")
l = [[1,2,3],[5,5,6]]
print(l)
print(l[0],1) #->0
print("numpy start")

#2d numpy

arr = np.array([[1,2,3],[5,5,6]])
print(arr)
print(arr[0,1])

list start
[[1, 2, 3], [5, 5, 6]]
[1, 2, 3] 1
numpy start
[[1 2 3]
 [5 5 6]]
2
