<a href="https://colab.research.google.com/github/Abhii009/Learn-Python/blob/main/day9_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [6]:
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[0:4])  #slicing
print(arr[-1])
print(arr[:3:2]) #start from 0 to 3 and jump 1
print(arr[::2])#jump by one
print(arr[::-1])#reverse
print(arr[3:5])

3
[1 2 3 4]
5
[1 3]
[1 3 5]
[5 4 3 2 1]
[4 5]


In [19]:
#2D
arr = np.array([[1,2,3],[4,5,6]])
#print(arr)
# print(arr[0:2]) #row
# print(arr[:,0]) #all rows | collumns
print(arr[:,1]) #row > 1 | collumns | jitane bhi rows hai uska 1st element print karvaya hai hamne
print(arr[0,:])

[2 5]
[1 2 3]


In [61]:
arr = np.array([[10,20],[30,40],])

print(arr[0,0])
print(arr[1,1])
print(arr[:,1])
print(arr[0,1,], arr[1,0]) #yaha [0,1] me 0th pura [10,20] bana hai, and 1th [30,40] | ab in dono ka 1st element print hua hai
print(arr[0,0,], arr[1,1])

10
40
[20 40]
20 30
10 40


In [69]:
arr = np.array([[10,20],[30,40],[50,60]])
print(arr[0,1], arr[1,0], arr[2,0])

20 30 50


In [134]:
#2d
import numpy as np

arr = np.array([[2453,75,183975],[5795,99,573705],[4100,36,147600],
                [7526,86,647236],[9528,45,428760],[10788,17,183396]])

print(arr[0,0], arr[0,1])
print()
print(arr[0,2],arr[1,1])
print()
print(arr[2,0],arr[2,0],arr[2,1],arr[3,2])
print()
print(arr[4,1],arr[5,1])
print()
print(arr[4,2],arr[5,2])


2453 75

183975 99

4100 4100 36 647236

45 17

428760 183396


In [124]:
import numpy as np
arr=np.array([[2453,75,183975],[5795,99,573705],[4100,36,14700],[7526,86,647236],[9528,45,428700],[10788,17,183396]])
# print(arr)
print(arr[[2,3,3],[0,0,1]])
print(arr[[0,0,5,5],[0,1,2,2]])
print(arr[[1,0],[1,2]])
print(arr[[4,5],[1,1]])


[4100 7526   86]
[  2453     75 183396 183396]
[    99 183975]
[45 17]


In [155]:
#3d

import numpy as np
arr = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
print(arr.ndim)  #3d
print(arr[0])
#print("=>", arr[0])
#print("=>>", arr[0,0])
#print("=>>>", arr[0,0,0]) # This would cause an IndexError as the array is 2D

3
[[1 2]
 [3 4]]


In [156]:
# 3d
import numpy as np
arr = np.array([
    [[1,2],
     [3,4]
    ],
    [[5,6],
     [7,8]
    ]
    ])
# print(arr.ndim) # 3d
# print("=>",arr[0]) # block
# print("=>>",arr[0,0]) # block -> row
# print("=>>>",arr[0,0,0]) # block -> row -> cols
#
print(arr[:,0]) # all block -> row -> 0
print(arr[:,:,0]) # all block -> all rows -> cols 0

[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [158]:
#for loop on numpy
#1d
arr = np.array([10,20,30,40])
print(arr)
for i in arr:
    print(i)


[10 20 30 40]
10
20
30
40


In [162]:
#2d
arr1 = np.array([[1,2],[3,4],[5,6]])
for i in arr1:
  for j in i:
    print(j)

1
2
3
4
5
6


In [163]:
#while loop in numpy
#1d
arr = np.array([10,20,30,40])
i = 0
while i < arr.size:
  print(arr[i])
  i+=1

10
20
30
40


In [161]:
#while loop in numpy
#2d
arr1 = np.array([[1,2],[3,4],[5,6]])
while i in arr1:
  while j in i:
    print(j)
    i+=1


6
6


In [178]:
#sorting
#1d
arr = np.array([10,20,30,40])
print(arr)
print(np.sort(arr)) #asending
print(np.sort(arr)[::-1]) #desending


#2d
arr1 = arr.reshape(2,2)
print(arr1)
print(np.sort(arr1,axis=0))

[10 20 30 40]
[10 20 30 40]
[40 30 20 10]
[[10 20]
 [30 40]]
[[10 20]
 [30 40]]


In [184]:
#filter  1d
import numpy as np
arr = np.array([10,20,30,40])
print(arr[0:3])
print(arr[arr>20])

[10 20 30]
[30 40]


In [188]:
#where
arr = np.array([10,20,30,40])
print(np.where(arr>20,"true","false"))


['false' 'false' 'true' 'true']


In [189]:
print(np.where(arr>20, arr*2,arr))

[10 20 60 80]
